import Head from "next/head"
import Header from "./header"
import BScroll from "../features/bScroll"
import Footer from "./footer"
import { useRouter } from 'next/router';
import HeaderOne from "./headerOne";


export default function Layout({ children }) {
    const router = useRouter();
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="main">
                <div id="wrapper">
                    <BScroll />
                    {router.pathname == '/home/one' ? <HeaderOne /> : <Header />}
                    <div className="no-bottom no-top" id="content">
                        <div id="top"></div>
                        {children}
                    </div>
                    <Footer />
                </div>
            </div>
        </>
    )
}